### ISSUE TITLE
Search is currently broken

### ISSUE THREAD

**Issue by wilzbach** [CyberShadow/bugzilla-meta#15]
![image](https://user-images.githubusercontent.com/4370550/37942817-46a5da44-3175-11e8-9fca-35320b32619a.png)

http://dbugs.k3.1azy.net/buglist.cgi?quicksearch=test&list_id=3

**Comment by CyberShadow** [comment]
Fixed in https://github.com/CyberShadow/bmo/commit/01d95dc075ab1b840786a6752d276f53cccb54d9
