### ISSUE TITLE
undef error - Can't locate object method "is_mentor" via package "Bugzilla::Bug"

### ISSUE THREAD

**Issue by wilzbach** [CyberShadow/bugzilla-meta#21]
http://dbugs.k3.1azy.net/show_bug.cgi?id=1

**Comment by CyberShadow** [comment]
How do I reproduce this?

**Comment by wilzbach** [comment]
Just click on the link:

![image](https://user-images.githubusercontent.com/4370550/37996405-d293aa2a-3217-11e8-97b6-15ad7f43ff93.png)

**Comment by CyberShadow** [comment]
I just get a working bug page! Something in your cookies?

**Comment by CyberShadow** [comment]
(Please back them up if you intend to clear them)

**Comment by wilzbach** [comment]
Sent a `curl` command to reproduce to you via Slack. I cleared them and logged in/out and it still happens.

**Comment by CyberShadow** [comment]
Fixed in https://github.com/CyberShadow/bmo/commit/955a40bfa29eeb81fcbcc9f9e3bf1f514e45dc4d.
