### ISSUE TITLE
Attaching files triggers an error

### ISSUE THREAD

**Issue by wilzbach** [CyberShadow/bugzilla-meta#23]
![image](https://user-images.githubusercontent.com/4370550/38166410-b2bc1b42-3523-11e8-9b11-d61dc0e00a9e.png)

Goto: http://dbugs.k3.1azy.net/show_bug.cgi?id=2 -> "Attach file"

**Comment by CyberShadow** [comment]
Fixed by https://github.com/CyberShadow/bmo/commit/994432d8594817edbc793a2dd73b4ea1ee8eb523.
